#!/usr/bin/env bash
# Score the free-text/path fix on a repo it has never seen.
#
# pylint-dev/pylint was chosen before the fix was written, on one criterion: it
# is the only SWE-bench repo whose labels are mixed-case ("Bug :beetle:",
# "Enhancement ✨"), so it can actually exercise the label defect. Its corpus and
# questions were generated by the unchanged v2 generator and frozen in
# SPLITS.sha256 before any of it was scored.
#
# A gives the pre-campaign reference. E reuses D's graph — they differ only in
# agent/config.ts, which the ingestion path never imports.
set -euo pipefail
cd "$(dirname "$0")/.."
set -a; . ./github_issue/.env; set +a

S=pylint-holdout
ATT=3
CONC=6

echo "== A-baseline__$S"
SUT_DIR=../.worktrees/baseline/github_issue bun verification_bench/run.ts \
  --split $S --job "A-baseline__$S" --attempts $ATT --qa-concurrency $CONC 2>&1 | tail -5

echo "== D-champion-enum__$S"
SUT_DIR=../.worktrees/champion-enum/github_issue bun verification_bench/run.ts \
  --split $S --job "D-champion-enum__$S" --attempts $ATT --qa-concurrency $CONC 2>&1 | tail -5
bun verification_bench/score-extraction.ts --split $S --job "D-champion-enum__$S" 2>&1 | tail -5

echo "== E-freetext-fix__$S"
SUT_DIR=../github_issue bun verification_bench/run.ts \
  --split $S --job "E-freetext-fix__$S" --attempts $ATT --qa-concurrency $CONC \
  --stage qa --keep-graph 2>&1 | tail -5

echo "SEALED RUN COMPLETE"
